---
- name: Install Docker
  apt: name="{{ item }}" update_cache=yes state=latest
  loop:
  - docker
  - docker.io
  - docker-compose
  - docker-registry
  when: ansible_distribution == "Debian"

#- name: Install Packages Redhat
#  yum: name="{{ item }}" update_cache=yes state=latest
#  loop:
#   - nginx
#   - mariadb-server
#   - php-fpm
#   when: ansible_distribution == "Redhat"
